### ISSUE TITLE
Unable to add Grabble script to game objects

### ISSUE THREAD

**Issue by octatone** [fariazz/zenvavr#3]
![image](https://user-images.githubusercontent.com/492289/69064256-2e482c80-0a1e-11ea-8faf-970324a7c5c3.png)

**Comment by kburton** [comment]
I'm seeing the same issue. I'm also seeing two compilation errors:
```
Assets/ZenvaVR/Toolkit/Scripts/AutoPoseSource.cs(36,26): error CS0117: 'InputDevices' does not contain a definition for 'GetDevicesWithCharacteristics'
Assets/ZenvaVR/Toolkit/Scripts/AutoPoseSource.cs(36,56): error CS0103: The name 'InputDeviceCharacteristics' does not exist in the current context
```
I'm on MacOS (10.14.02) just in case that's related. Unity version `2019.2.12f1`.

None of the ZenvaVR scripts appear in the `Add Component -> Scripts` menu.

**Comment by octatone** [comment]
@DanielBuckley101 @fariazz are you seeing the issues I have filed?

**Comment by DBuckley101** [comment]
Hey there @octatone and @kburton . The reason for these errors, is because the Zenva VR library was developed with Unity 2019.3. In 2019.3, there are a few changes to the UnityEngine.XR library, causing previous code to be deprecated. So changes such as implementing 'GetDevicesWithCharacteristics' was needed. This is also probably the cause of not being able to attach the scripts since there would be problems with the compiling.

Switching over to 2019.3 or later should fix this issue. Right now 2019.3 is in beta, although it will become the official build very soon. Hope this helps.
